spring.application.name=agrocloud-backend

# Conexión a Base de Datos con respaldo a localhost
spring.datasource.url=${DB_URL:${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:15432/agrocloud_db}}
spring.datasource.username=${DB_USERNAME:${SPRING_DATASOURCE_USERNAME:agrocloud_user}}
spring.datasource.password=${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD:agrocloud_secure_pass_2026}}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect